add redis
DnicheDirector/seller pull request #6
Opened 2022-12-12 06:51 UTC by DnicheDirector

2022-12-13 08:43 UTC, viktor-dobroselsky requested changes

2022-12-13 08:43 UTC, viktor-dobroselsky commented on user-transaction-service/src/main/java/com/seller/usertransactionservice/configuration/RedisConfiguration.java
> +    private final RedisProperties redisProperties;
Раз уж это конфиг - то лучше RedisProperties затолкай как один из аргументов метода defaultCacheConfiguration. У конфиг файлов свой стиль, придерживася ему

2022-12-13 08:43 UTC, viktor-dobroselsky commented on user-transaction-service/src/main/java/com/seller/usertransactionservice/configuration/RedisProperties.java
> +    private int ttlInMinutes;
Нет валидации, и рекомендую использовать Duration.  Этот класс позволяет тебе прописывать удобно небольшие врмененные промежутки в удобном формате (1m30s90ms)

2022-12-13 08:43 UTC, viktor-dobroselsky commented on user-transaction-service/src/main/java/com/seller/usertransactionservice/exceptionhandler/GlobalExceptionHandler.java
> +import java.time.ZonedDateTime;
Лишний импорт, я так понимаю

2022-12-13 14:21 UTC, DnicheDirector commented on user-transaction-service/src/main/java/com/seller/usertransactionservice/exceptionhandler/GlobalExceptionHandler.java
> +import java.time.ZonedDateTime;
неа, тут всё ок. Просто в прошлом коммите каким-то образом эти классы оказались неимпортироваными

2022-12-14 08:27 UTC, viktor-dobroselsky approved these changes

2022-12-14 09:07 UTC, merged